### ISSUE TITLE
OS X 打开了并不能搜索或者播放

### ISSUE THREAD

**Issue by MMMartt** [MingtaoFu/Netease_music#1]
如题_(:з」∠)_
可能是使用方法不对？

**Comment by MingtaoFu** [comment]
能否把终端 log截个图或复制一下。或者界面截个图，看是否成功渲染

**Comment by MMMartt** [comment]
```
[0:16:28] Martin:Netease_music git:(master) $ nwjs .

module.js:359
    throw err;
    ^
Error: Cannot find module 'url-valid'
    at Function.Module._resolveFilename (module.js:357:15)
    at Function.Module._load (module.js:303:25)
    at Module.require (module.js:385:17)
    at require (internal/module.js:20:19)
    at /Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:11:15
    at Object.<anonymous> (/Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:42:2)
    at Module._compile (module.js:431:34)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39
K(a),"modulesToLoad","not an array");var b=[],c;n(a,function(a){function d(a){var b,c;b=0;for(c=a.length;b<c;b++){var e=a[b],f=r.get(e[0]);f[e[1]].apply(f,e[2])}}if(!m.get(a)){m.put(a,!0);try{G(a)?(c=Tb(a),b=b.concat(g(c.requires)).concat(c._runBlocks),d(c._invokeQueue),d(c._configBlocks)):D(a)?b.push(r.invoke(a)):K(a)?b.push(r.invoke(a)):Ta(a,"module")}catch(e){throw K(a)&&(a=a[a.length-1]),e.message&&e.stack&&-1==e.stack.indexOf(e.message)&&(e=e.message+"\n"+e.stack),Ga("modulerr",a,e.stack||e.message||
                                                                                                                                                                                                                                                                                                                                                                             ^

Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0-rc.0/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.0-rc.0%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A6%3A421%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A24%3A99%0A%20%20%20%20at%20b%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A149)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A392%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A201%0A%20%20%20%20at%20n%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A7%3A344)%0A%20%20%20%20at%20g%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A49)%0A%20%20%20%20at%20fb%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A42%3A360)%0A%20%20%20%20at%20c%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A19%3A421)
    at Error (native)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:6:421
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:475
    at n (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:7:344)
    at g (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:49)
    at fb (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:42:360)
    at c (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:421)
    at zc (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:20:225)
    at be (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:41)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:303:112
Error: Cannot find module 'url-valid'
    at Function.Module._resolveFilename (module.js:357:15)
    at Function.Module._load (module.js:303:25)
    at Module.require (module.js:385:17)
    at require (internal/module.js:20:19)
    at /Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:11:15
    at Object.<anonymous> (/Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:42:2)
    at Module._compile (module.js:431:34)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39
K(a),"modulesToLoad","not an array");var b=[],c;n(a,function(a){function d(a){var b,c;b=0;for(c=a.length;b<c;b++){var e=a[b],f=r.get(e[0]);f[e[1]].apply(f,e[2])}}if(!m.get(a)){m.put(a,!0);try{G(a)?(c=Tb(a),b=b.concat(g(c.requires)).concat(c._runBlocks),d(c._invokeQueue),d(c._configBlocks)):D(a)?b.push(r.invoke(a)):K(a)?b.push(r.invoke(a)):Ta(a,"module")}catch(e){throw K(a)&&(a=a[a.length-1]),e.message&&e.stack&&-1==e.stack.indexOf(e.message)&&(e=e.message+"\n"+e.stack),Ga("modulerr",a,e.stack||e.message||
                                                                                                                                                                                                                                                                                                                                                                             ^

Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0-rc.0/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.0-rc.0%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A6%3A421%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A24%3A99%0A%20%20%20%20at%20b%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A149)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A392%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A201%0A%20%20%20%20at%20n%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A7%3A344)%0A%20%20%20%20at%20g%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A49)%0A%20%20%20%20at%20fb%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A42%3A360)%0A%20%20%20%20at%20c%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A19%3A421)
    at Error (native)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:6:421
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:475
    at n (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:7:344)
    at g (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:49)
    at fb (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:42:360)
    at c (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:421)
    at zc (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:20:225)
    at be (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:41)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:303:112
Error: Cannot find module 'url-valid'
    at Function.Module._resolveFilename (module.js:357:15)
    at Function.Module._load (module.js:303:25)
    at Module.require (module.js:385:17)
    at require (internal/module.js:20:19)
    at /Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:11:15
    at Object.<anonymous> (/Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:42:2)
    at Module._compile (module.js:431:34)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39
K(a),"modulesToLoad","not an array");var b=[],c;n(a,function(a){function d(a){var b,c;b=0;for(c=a.length;b<c;b++){var e=a[b],f=r.get(e[0]);f[e[1]].apply(f,e[2])}}if(!m.get(a)){m.put(a,!0);try{G(a)?(c=Tb(a),b=b.concat(g(c.requires)).concat(c._runBlocks),d(c._invokeQueue),d(c._configBlocks)):D(a)?b.push(r.invoke(a)):K(a)?b.push(r.invoke(a)):Ta(a,"module")}catch(e){throw K(a)&&(a=a[a.length-1]),e.message&&e.stack&&-1==e.stack.indexOf(e.message)&&(e=e.message+"\n"+e.stack),Ga("modulerr",a,e.stack||e.message||
                                                                                                                                                                                                                                                                                                                                                                             ^

Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0-rc.0/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.0-rc.0%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A6%3A421%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A24%3A99%0A%20%20%20%20at%20b%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A149)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A392%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A201%0A%20%20%20%20at%20n%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A7%3A344)%0A%20%20%20%20at%20g%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A49)%0A%20%20%20%20at%20fb%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A42%3A360)%0A%20%20%20%20at%20c%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A19%3A421)
    at Error (native)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:6:421
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:475
    at n (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:7:344)
    at g (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:49)
    at fb (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:42:360)
    at c (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:421)
    at zc (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:20:225)
    at be (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:41)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:303:112
Error: Cannot find module 'url-valid'
    at Function.Module._resolveFilename (module.js:357:15)
    at Function.Module._load (module.js:303:25)
    at Module.require (module.js:385:17)
    at require (internal/module.js:20:19)
    at /Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:11:15
    at Object.<anonymous> (/Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:42:2)
    at Module._compile (module.js:431:34)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39
K(a),"modulesToLoad","not an array");var b=[],c;n(a,function(a){function d(a){var b,c;b=0;for(c=a.length;b<c;b++){var e=a[b],f=r.get(e[0]);f[e[1]].apply(f,e[2])}}if(!m.get(a)){m.put(a,!0);try{G(a)?(c=Tb(a),b=b.concat(g(c.requires)).concat(c._runBlocks),d(c._invokeQueue),d(c._configBlocks)):D(a)?b.push(r.invoke(a)):K(a)?b.push(r.invoke(a)):Ta(a,"module")}catch(e){throw K(a)&&(a=a[a.length-1]),e.message&&e.stack&&-1==e.stack.indexOf(e.message)&&(e=e.message+"\n"+e.stack),Ga("modulerr",a,e.stack||e.message||
                                                                                                                                                                                                                                                                                                                                                                             ^

Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0-rc.0/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.0-rc.0%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A6%3A421%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A24%3A99%0A%20%20%20%20at%20b%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A149)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A392%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A201%0A%20%20%20%20at%20n%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A7%3A344)%0A%20%20%20%20at%20g%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A49)%0A%20%20%20%20at%20fb%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A42%3A360)%0A%20%20%20%20at%20c%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A19%3A421)
    at Error (native)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:6:421
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:475
    at n (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:7:344)
    at g (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:49)
    at fb (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:42:360)
    at c (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:421)
    at zc (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:20:225)
    at be (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:41)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:303:112
Error: Cannot find module 'url-valid'
    at Function.Module._resolveFilename (module.js:357:15)
    at Function.Module._load (module.js:303:25)
    at Module.require (module.js:385:17)
    at require (internal/module.js:20:19)
    at /Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:11:15
    at Object.<anonymous> (/Users/Martin/Files/Codes/Netease_music/scripts/lib/download.js:42:2)
    at Module._compile (module.js:431:34)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39
K(a),"modulesToLoad","not an array");var b=[],c;n(a,function(a){function d(a){var b,c;b=0;for(c=a.length;b<c;b++){var e=a[b],f=r.get(e[0]);f[e[1]].apply(f,e[2])}}if(!m.get(a)){m.put(a,!0);try{G(a)?(c=Tb(a),b=b.concat(g(c.requires)).concat(c._runBlocks),d(c._invokeQueue),d(c._configBlocks)):D(a)?b.push(r.invoke(a)):K(a)?b.push(r.invoke(a)):Ta(a,"module")}catch(e){throw K(a)&&(a=a[a.length-1]),e.message&&e.stack&&-1==e.stack.indexOf(e.message)&&(e=e.message+"\n"+e.stack),Ga("modulerr",a,e.stack||e.message||
                                                                                                                                                                                                                                                                                                                                                                             ^

Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0-rc.0/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.0-rc.0%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A6%3A421%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A24%3A99%0A%20%20%20%20at%20b%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A149)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A23%3A392%0A%20%20%20%20at%20chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A201%0A%20%20%20%20at%20n%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A7%3A344)%0A%20%20%20%20at%20g%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A39%3A49)%0A%20%20%20%20at%20fb%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A42%3A360)%0A%20%20%20%20at%20c%20(chrome-extension%3A%2F%2Ffmfjlapkdhgcfepiiikabmbfeojipdkn%2Fscripts%2Fangular.min.js%3A19%3A421)
    at Error (native)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:6:421
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:475
    at n (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:7:344)
    at g (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:39:49)
    at fb (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:42:360)
    at c (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:421)
    at zc (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:20:225)
    at be (chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:19:41)
    at chrome-extension://fmfjlapkdhgcfepiiikabmbfeojipdkn/scripts/angular.min.js:303:112
```

图片在这儿[0-0](http://o6tfgfxj3.bkt.clouddn.com/FuMineTaoNeteaseMusicErrorPic.png)
